# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "1.75"
components = [ "rust-src", "rustfmt", "llvm-tools", "miri" ]
targets = ["thumbv7m-none-eabi", "x86_64-unknown-linux-gnu"] # https://en.wikipedia.org/wiki/ARM_Cortex-M#Cortex-M3
